name: tsam_env
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.15
  - pip
  # Core dependencies
  - scikit-learn >=1.3.0,<=1.8.0
  - pandas >=2.2.0,<=3.0.0
  - numpy >=1.22.4,<=2.4.1
  - pyomo >=6.4.3,<=6.95
  - networkx >=2.5,<=3.6.1
  - tqdm >=4.21.0,<=4.67.2
  - highspy >=1.7.2,<=1.12.0
  - matplotlib
  - plotly >=5.0.0
