name: tsam_env
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - pip
  # Core dependencies
  - scikit-learn>=0.0
  - pandas>=2.1.0
  - numpy>=1.21.0
  - pyomo>=6.8
  - networkx
  - tqdm
  - highspy
  - matplotlib
