on:
    workflow_dispatch:
    push:
        branches: ["test_dependency_range_v_3_0"]
    pull_request:
        branches: ["master"]

jobs:
    TestPushCondaForgeDev:
        name: Test conda-forge development version on ${{ matrix.runner_tag }}
        strategy:
            fail-fast: false
            matrix:
                runner_tag: ["self-hosted"]
                library_version:
                    [
                        "4.10.0",
                        "4.11.0",
                        "4.11.1",
                        "4.11.2",
                        "4.12.0",
                        "4.13.0",
                        "4.14.0",
                        "4.15.0",
                        "4.16.0",
                        "4.17.1",
                        "4.18.0",
                        "4.19.1",
                        "4.19.2",
                        "4.19.4",
                        "4.19.5",
                        "4.19.6",
                        "4.19.7",
                        "4.19.8",
                        "4.19.9",
                        "4.20.0",
                        "4.21.0",
                        "4.22.0",
                        "4.23.0",
                        "4.23.1",
                        "4.23.2",
                        "4.23.3",
                        "4.23.4",
                        "4.24.0",
                        "4.25.0",
                        "4.26.0",
                        "4.27.0",
                        "4.28.0",
                        "4.28.1",
                        "4.29.0",
                        "4.29.1",
                        "4.30.0",
                        "4.31.0",
                        "4.31.1",
                        "4.32.0",
                        "4.32.1",
                        "4.32.2",
                        "4.33.0",
                        "4.34.0",
                        "4.35.0",
                        "4.36.1",
                        "4.37.0",
                        "4.38.0",
                        "4.39.0",
                        "4.40.0",
                        "4.40.1",
                        "4.40.2",
                        "4.41.0",
                        "4.41.1",
                        "4.42.0",
                        "4.42.1",
                        "4.43.0",
                        "4.44.0",
                        "4.44.1",
                        "4.45.0",
                        "4.46.0",
                        "4.46.1",
                        "4.47.0",
                        "4.48.0",
                        "4.48.1",
                        "4.48.2",
                        "4.49.0",
                        "4.50.0",
                        "4.50.1",
                        "4.50.2",
                        "4.51.0",
                        "4.52.0",
                        "4.53.0",
                        "4.54.0",
                        "4.54.1",
                        "4.55.0",
                        "4.55.1",
                        "4.55.2",
                        "4.56.0",
                        "4.56.1",
                        "4.56.2",
                        "4.57.0",
                        "4.58.0",
                        "4.59.0",
                        "4.60.0",
                        "4.61.0",
                        "4.61.1",
                        "4.61.2",
                        "4.62.0",
                        "4.62.1",
                        "4.62.2",
                        "4.62.3",
                        "4.63.0",
                        "4.63.1",
                        "4.63.2",
                        "4.64.0",
                        "4.64.1",
                        "4.65.0",
                        "4.65.1",
                        "4.65.2",
                        "4.66.0",
                        "4.66.1",
                        "4.66.2",
                        "4.66.4",
                        "4.66.5",
                        "4.66.6",
                        "4.67.0",
                        "4.67.1",
                        "4.7.2",
                        "4.7.4",
                        "4.7.6",
                        "4.8.1",
                        "4.8.2",
                        "4.8.4",
                        "4.9.0",
                    ]
        uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
        with:
            runner_tag: ${{ matrix.runner_tag }}
            requirements_file_name: environment.yml
            examples_to_execute: "docs/source/examples_notebooks/aggregation_example.ipynb docs/source/examples_notebooks/aggregation_method_showcase.ipynb docs/source/examples_notebooks/aggregation_optiinput.ipynb docs/source/examples_notebooks/aggregation_representation.ipynb docs/source/examples_notebooks/aggregation_segmentation.ipynb docs/source/examples_notebooks/example_k_maxoids.ipynb docs/source/examples_notebooks/predefined_sequence_example.ipynb"
            multiprocessing_example_string: "-n auto"
            library_version: ${{ matrix.library_version }}
            dependency_position_env_file: "7"
            library_name: "tqdm"
            multiprocessing_pytest_string: "-n auto"
